### ISSUE TITLE
'Expected "dummyValue" to be "dummyvalue"' error after update to 20.0.0

### ISSUE THREAD

**Issue by marco-streng** [stylelint/stylelint-config-standard#138]
> Clearly describe the bug

After updating to v20.0.0 the following error is thrown multiple times. All styling is done with `styled-components`
It seems that the error appears when i check component props or use styling from a variable (please see example below)

```shell
14:37  ✖  Expected "dummyValue" to be "dummyvalue"   value-keyword-case
29:19  ✖  Expected "dummyValue" to be "dummyvalue"   value-keyword-case
```

> Which rule, if any, is the bug related to?

` value-keyword-case`

> What CSS is needed to reproduce the bug?

```
14  ${props => props.icon && css`
15    align-items: center;
16    display: inline-flex;
17    line-height: 1;
18    vertical-align: middle;
19  `}
````

```
28  const ExternalLink = styled.a`
29    ${linkStyling}
30  `
````

> What configuration is needed to reproduce the bug?

```json
{
  "processors": ["stylelint-processor-styled-components"],
  "plugins": [
    "stylelint-order"
  ],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ],
  "rules": {
    "order/properties-alphabetical-order": true
  }
}
```

> Which version of stylelint are you using?

`20.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`cross-env stylelint 'src/**/*.js`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

`styled-components`

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
14:37  ✖  Expected "dummyValue" to be "dummyvalue"   value-keyword-case
29:19  ✖  Expected "dummyValue" to be "dummyvalue"   value-keyword-case
````

**Comment by jeddy3** [comment]
@marco-streng Thanks for the clearly written report and for using the template.

The styled-components processors is introducing the `dummyValue`.

We're [discouraging the use of processors](https://stylelint.io/user-guide/configure#processors) in favour of the built-in syntaxes. However, it's not that clear cut as the built-in syntax for CSS-in-JS has:

- [bugs to squash](https://github.com/stylelint/stylelint/issues/4574)
- [features to add for parity](https://github.com/stylelint/postcss-css-in-js/issues/3)

I recommend trying to see if you can use stylelint on your code without the processor. If that proves problematic, you can either:

- [turn the `value-keyword-value` rule of completely](https://stylelint.io/user-guide/configure#rules)
- [configure it to ignore these keywords](https://stylelint.io/user-guide/rules/value-keyword-case#ignorekeywords-regex-regex-non-regex)

You can do the former with:

```json
{
  "rules": { "value-keyword-case": null }
}
```

And the latter with:

```json
{
  "rules": { "value-keyword-case": ["lower", { "ignoreKeywords": ["dummyValue"] }] }
}
```

If removing the processor does prove problematic, please can you tell us about your experience especially if you uncover bugs that are not already documented in https://github.com/stylelint/stylelint/issues/4574, so that we can improve the built-in CSS-in-JS syntax in preparation for the eventual deprecation of the processors.

**Comment by HosseinAgha** [comment]
@jeddy3 I don't use styled-components processors and plugins my config is as simple as this:  

```js
module.exports = {
  extends: ['stylelint-config-standard'],
};
```

But I get the above error whenever I try to use a camelCase prop in my styled-component css. I think you cannot distinguish between the css attributes and js variables.   

```jsx
const StyledComp = styled.div`
  background: ${({ isSubPart, theme }) => !isSubPart && theme.pallette.primary};
  border-radius: 0px 4px 4px 0px;
`;
```
I get the following error in the above code which is wrong:  
`Expected "isSubPart" to be "issubpart" (value-keyword-case)`

**Comment by adammo94** [comment]
I've came across this problem as well. Any progress?
