### ISSUE TITLE
No value for selector-list-comma-space-after

### ISSUE THREAD

**Issue by dylanzt** [stylelint/stylelint-config-standard#148]
> What is the problem you're trying to solve?

`selector-list-comma-space-after` is the only `*-comma-space-after` rule not present. I'm not sure if this is for some reason I'm not aware of, but it seems odd to be missing when all other `*-comma-space-after`, `*-comma-space-before`, and `*-comma-newline-after` permutations seem to be present.

> What solution would you like to see?

| Rule Added | Commit |
|---|---|
| `"selector-list-comma-space-after": "always-single-line",` | https://github.com/dylanzt/stylelint-config-standard/commit/bdf6198518b854723c13a4d370c56546b2ee8b1d |

**Comment by jeddy3** [comment]
@dylanzt Thanks for the digging into the config and for using the template.

> I'm not sure if this is for some reason I'm not aware of

It's because the config _always_ enforces multi-line selector lists (see [this demo](https://stylelint.io/demo#N4Igxg9gJgpiBcICGAaABAIzcNkA2EATvGgMQBmlA3GgL4A6AdiCiAM4CejALkgB4JwbNi3ARG5AJYBzQcCZo09EIQCueGG2Ul5jRYuVJuAWjUbjjCMdWMA1pYDujbWm5qYKBfuUYCYWxZWMAC2AA7cHC5uqh5eBmIEhIHGkowAbkh4klDGABYwfFHunnreYsHBMDzJIeGRCK7FcUogsGB4SIRGkuLGvhD+yVCqoVlgRjDGoYQQoTCE3JKaLgDazYrRsaX62OtlMpaEMKt7O8qQjGwwYKqLaZPDo5Lj3JrGDpLcucZQkpTzVRMGTwMS0IFOaAAunsGNsoSUzq1rh0uotev1BpZjGxckQvkhGDlprN5hFjBB7oRCNllg1NgiyuRxCZyEhgpI8BwhiMxhMLGzaSR6c1lEzqqz2ZzkuzhKlpMZpFV5s9jBKOVzbDAOA4iFAijEGfFyDYwGjGMZxngwMlUsDsvqtojjYxTT1zZbrVibGxQkgwDAciTUUQHYaWs7Xb0sowYJ0FV1foDkpZLrxCZ0cr8jpHnHSmnDlJqOOQupUfsjOt1eljJGE8QTuKGRSBKr8kKrY9xVEd+WWvXZHLmhfnEVjYGx-YS5di5mA-s9PvVhwbm2Oec8+UYUnWFqZ1ILGiuCyA108XpMrhpTUQwcvHWUsbUyWwIN3-U3j4++G521d2fhxFvQ973iGt0kybIflfXwLw6HELQgCpASA4Vj2JOYFi5ft7AgJwP0RS9rm4IgpiuVQoCsdokGEZIbBwvC8yPAiYCvYiklCMiKOMFiQiTbDB3wspCOvJIIjmWiB1wodgLDZQ2DcacsRjBxo2ORiQJaGxPgk+jpNQxEtzMSYny5VS+hgJkjhOOF4kyBwkA4MEw0UXQdkRAp-XCay3Lcnw-FsDQaKQchXiSNgBV7SYMQCzQnIhI1JEIeSLE0V49XBGz9EhZz9mkQ41JINZMoMkL5gQpCeGUCFoUy2Edmy5tDP3SKLWogqWgIBx5mUWTkBMIyWp9P1JmC0KXEMPB7Mc7E5XMVSesa-rmr-Z4IAIc1lLM0buoaCapri49ootAg2GnDAun9biwjJMyMAsoh2uUGNKQWw7-OOiBTsYeVzuGlKVNSEbSsIcbkEmhyDsRI72k+s6LsmTbAfMyzHrB-bjGCdRFmMeaWGbaGTrhv6hsuu6UdBuyIZm765sB16ofeklGCJy7EZjYxtpB3a0apzG8Gx3HeqOpmWYvX1Ls5inwemr7pFpmN6bKYW5mZ76+nhmc-rJh6pf2xX4gApJ8j4VqrlBzqdt6w28gKHGqmkL5QZxPF9ZaSAKpMEycaR7WrIaIqfL2iHXZciFlA8mAvP9+Lw0S5KY3kgMquK+Ew5AA4dejlP4nkjgNGjEx3eCAkoDBaqYWaBrjyLpMHFyT5NHFyZUlO2BdeDvHq9UeTEKmGYMLJL3bvuv3Cr2IPHJD3YU-DvhPMbLOfJK0KLW74jgj7oMIinp045MBO0uTpfU5n9O8szsfs5aTnysqSrO+P+IW5pam5cmW7-KPpeap8uqst6toKIqzmgwASeUJMgZjW5s9S2zZAGVjNH0MBmtSYj1RpTSeD8yjwNRG6Po70VoAQ2jAAG7NJbcwwWwDGWNJDewVlg+IODgH4IGAEQha1egQI5sDduMtZrvzpgwloTDEFHXYetFBUU0GgxgVzABFZcHogIfwuhkxi4mxEW6ICABGeRVFFEgPej+Dk05xHiF4ZDbBCjmFEP+ltHhFDpZUL5gLQReigGINsVw8hJAJ5UNlvLNS7iEF4K8U3ZGF8WiyNdsoTRvQh4+2kYvXyPNME5VckvWe89vKP0MMDcs+jgE70ZHvFKid0rVRyk-c+o80AB1ycgfJNd75VP2JcF+ASBHs2il-HyP83J-0UFXJ0JpPGIWLnYpGPjr5OOofzWhgtmwRjGRUX84Tpl+NfoEmJIBlmhPGWsrWSTfEnhgC9IRopRl4PUVdOoqigIAAZep7OrBFcYZtuYWzkUsq5vRfRHB4PkK4VC2bN3aW3Rx6MXELLcT8l0iD-mAiBW8Lhz8IUnNkVsrpQS4U5nePXV43iHEnMoTs1IsAeBFIaAAJl6hob6XxjAAC95hWH7J8QS8QbkJITi4XRzZWySHbOQTs3ZJhhL+hs1JliuUBiFR2IwYqEISK4b7VG0SLktjlcK0VPZGBvLaubXCsDjyCp1YqnsiLAWaBReEtF6qzkmsRGahVXYexdG+pMIMRgSJEqgSSpxOyXUiotZMD1ipyQYR9WFcJaqLFBu1cYAAjjEQgplJDJSLu2UF3D-UzKhTQ1RCa2zJtTemzNBzJG5p2gG9GnSi2apdSm+Y5bC6VtVccqJjrvmfiCGtfFDcIGcqiVYGUstuKEnJOQbEr5CCsxIbjO8vVGCqGCHdJIGgkC-DViymY8bNUrrXWVLExjozyl3Z9Ydyh0Kki5O81GXydkDR5VI8mySDKzOhQ29JacI5R0vo-WOSV96pSThlY+wzMln3yjk4+eSV7NIXuXWqlderCTYhzbgCkMC3CihdTU3B-F2vBQ685aGeIiUw9h3Dkb5jRqrVKjV5HWIkSMNR14tHgwxqOW+jF3adnoZIu7DAqR6N+prfmjuzGiJCcQiJ-VGGO28ck2k5sgmkjjknFABs5V5P0aUpwpuV72AUYw1kCtqzJlkOJSpmVLR1PewsxMpTkSnr8c1Q57l11028oaE8tTpmSIcRgORSicEqH3qNV1HtzEWPsU4mF6iVCrVfBtURv69qZHuek5R4LoXuIaDvoXQ1nzjUxaEoF+LIWuI8SK8q6sEBeBmlBhRVQMEBOVeMGJcVJWTmPs1VpYrHy+tlZ2cCGIxgiw6kIDkSLpXotjcyBN8zbbLM5qlZQuZrj6G9XGwIpzhyJY2c2fWxZx49uOdW852Nna3NkebBdlbGN+C3JuoDR5XhYS0BALQIAA)), whereas the other permutations allow for both single-line and multi-line things.

The `*-newline-after` rule for selector lists uses `"always"` for its primary option, whereas the other permutations use `"always-multi-line"`:

https://github.com/stylelint/stylelint-config-standard/blob/55b1d13741140c98c9b5b322cd4efbae43aea25c/index.js#L95-L96

https://github.com/stylelint/stylelint-config-standard/blob/55b1d13741140c98c9b5b322cd4efbae43aea25c/index.js#L105-L107

If you'd prefer to allow both multi-line and single-line selector lists, you can configure stylelint like so:

```
"selector-list-comma-newline-after": "always-multi-line", 
"selector-list-comma-space-after": "always-single-line", 
"selector-list-comma-space-before": "never", 
```

Which will allow both:

```
a, b {}

c,
d {}
```

Not allowing both is more common across style guides, and is why this config doesn't allow it. I hope that makes sense.

I'll close the issue for now.

**Comment by dylanzt** [comment]
Makes sense @jeddy3, I missed that difference in config. Cheers.
