### ISSUE TITLE
Remove deprecated rules

### ISSUE THREAD

**Issue by MarkSky** [stylelint/stylelint-config-standard#244]
### What is the problem you're trying to solve?

From the [Stylistic issues](https://stylelint.io/user-guide/rules/list/#stylistic-issues) website, some rules won't be handled in the future.
Could remove these rules from stylelint-config-standard?

### What solution would you like to see?

When using stylelint-config-standard, there're no errors about the frozen rules.

**Comment by carlosjeurissen** [comment]
@jeddy3 If this change is pushed thru. It would be very welcome if we can make a smooth transition to one new stylelint-plugin-stylistic (or something) plugin which contains all the stylistic rules which will be removed as to have a viable alternative to the removed rules which would be fully customizable (unlike prettier).

**Comment by Mouvedia** [comment]
I am probably in the minority but I gotta say that having to review 64 rules at once to know which ones I wanna keep is annoying. The result, for me, is that I am probably not gonna rely on stylelint-config-standard anymore for my personal config because the maintenance burden of version upgrades is becoming too time consuming that it outweighs the PROs of extending it.
