### ISSUE TITLE
Restore `declaration-block-single-line-max-declarations` removed on 30.0.0

### ISSUE THREAD

**Issue by elirasza** [stylelint/stylelint-config-standard#285]
### What steps are needed to reproduce the bug?

Upgrade from 29.0.0 to 30.0.0

### What did you expect to happen?

The declaration-block-single-line-max-declarations rule should have still been present

### What actually happened?

In the changelog regarding 30.0.0, it is said 64 rules were removed because they are now deprecated by stylelint. I noticed one of them, `declaration-block-single-line-max-declarations`, [does not seem to be in the deprecation list](https://stylelint.io/user-guide/rules/declaration-block-single-line-max-declarations). Is this an error ? Or was its removal on purpose, but for another reason than deprecation ?

**Comment by ybiquitous** [comment]
@elirasza Thanks for the report. As you pointed, the [`declaration-block-single-line-max-declarations`](https://stylelint.io/user-guide/rules/declaration-block-single-line-max-declarations) rule is not about a stylistic convention and so not deprecated. The rule is categorized in [Max & min](https://stylelint.io/user-guide/rules#max--min).

I guess the rule was accidentally removed since the original issue about this deprecation (https://github.com/stylelint/stylelint/issues/5674) didn't mention this rule.

Restoring the rule sounds good to me for now, but I'd like to hear others' opinions. If nobody has objections, let's restore it.

By the way, there seems to be no problem in the case when used with Prettier together since [Prettier formats a single line to multiple lines](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMdkA2EBOS6ADgJZQDWA3OgO6kAmMAFkagK4wQ0C+IANCAjEYpaAGdkoVPnwRaABRkJJKVDlqoAnpMEAjfKjAU4MAMqoAtnAAy5OMgBm68XH2Hjps8SPkA5sgw+OxuIHCWenAMDFE2qFB+7Kh+cABiBJaoMKIJyGicEAIgzDCWOADqzKTw4j5gcGYq1aQAbtVaeWDiuiDkrvgwCoZ+mU4uoQBW4gAeZv44cACK7BDwYziugj74-Z3dRcT45DDljCzIABwADFtyruWGxHmHcP0tDoIAjivwQ8KqaHEAFooHAolEivg4N9SFChslRkhnBtQq5LKRAsFUfM4ABBbJHPScOAKOD4Oyg9abEDiHHLVYOJHjQQwVB6U5MZjIABMLMMpBw-gAwhBLIiwuIAKxFdiuAAqbNUyOpLRCAEkoDFYGYwEcRLjNWYYFoFlS4DweEA).

**Comment by ybiquitous** [comment]
The rule was removed with PR #277.
