### ISSUE TITLE
Make this available as a '.stylelintrc' for easy installation

### ISSUE THREAD

**Issue by coliff** [stylelint/stylelint-config-standard#38]
I'd like to quickly and easily use these rules in my project without installing modules from NPM. Can you make this available as a .stylelintrc so we can quickly copy and paste it?

**Comment by coliff** [comment]
Update: I found that I could copy the rules from index.js to a new .stylelintrc file. Maybe this could be documented?

**Comment by jeddy3** [comment]
> Maybe this could be documented?

I'm not sure this is wise. There are advantages to using `npm`, rather than copying and pasting. Mainly the ease of installing a new version e.g. `npm install --save-dev stylelint-config-standard@latest`. As we release a new version of this config alongside each release of stylelint, it means both the linter and this config can be easily updated the same way.
