### ISSUE TITLE
Use ignore: "consecutive-duplicates-with-different-values" option for declaration-block-no-duplicate-properties

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-config-standard#42]
Ref: https://github.com/MoOx/phenomic/pull/741#r78704693

**Comment by davidtheclark** [comment]
I'm in favor of the switch. Consecutive duplicates are so easy to spot they're probably reliably intentional.

**Comment by jeddy3** [comment]
Groovy. I'll make the change and release alongside the next stylelint release.

**Comment by ntwb** [comment]
Added PR, this "could" ship in v13.1.0 now could it it not? (The option was added in stylelint 7.2.0)

That said it not necessarily "needs" to ship, I'm just thinking out loud from a semantic versioning point of view, the change is a less restrictive rule that would not break backwards compatibility.

**Comment by jeddy3** [comment]
> ship in v13.1.0 now could it it not? 

Yes, you're right.

**Comment by ntwb** [comment]
I just read the above after updating the PR, hence I used `HEAD` in the changelog 😏

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint-config-standard/issues/43

**Comment by ntwb** [comment]
@jeddy3 Nice pickup on releasing as `13.0.1` rather than `13.1.0` 

> Patch release (intended to not break your lint build)
> > A bug fix in a rule that results in stylelint reporting fewer errors.

**Comment by jeddy3** [comment]
> Nice pickup on releasing as 13.0.1 rather than 13.1.0

Yep, I saw that at the last moment :)

**Comment by ArmorDarks** [comment]
I'm surprised that this change made it way into standard config. This use case is exception, and it should be handled as exception — via disabling rule on line explicitly, not by allowing any duplicates with different values.

**Comment by MoOx** [comment]
I don't agree. This pattern is very common to handle fallbacks when browser can't handle a value. Sometimes autoprefixer is not enough & relying on this make a lot of sense imo. position sticky is an example, but you will find a lot of other example when playing with bleeding edges css props :)

**Comment by ArmorDarks** [comment]
For this cases you can switch off linting of certain lines.

Stylelint can't know is it a valid hack, or is it accident error. Unfortunately, the last one case much more common than hacks in large teams. Stylelint should assume worst scenario, and in our case that it's an error. If developer finds out `stylelint-disable-line` rule right near that line, he will be certain that it's intentional hack, otherwise it would be simple an error, overlooked by developer and now by Stylelint too.

**Comment by MoOx** [comment]
Who can miss a duplicate property when they are following each others?

**Comment by ArmorDarks** [comment]
Same thing can be said about most linters checks. "How stupid my teammate should be to make that idiotic typo?!", right? If those errors and duplicates are so obvious, why would we need linters at first place?

My point, is that "that error easy to spot" should be last argument for justification of linters behavior.

**Comment by davidtheclark** [comment]
> Unfortunately, the last one case much more common than hacks in large teams.

Sorry, @ArmorDarks, but I think we just disagree on that point. Duplicate properties in general might be most often a mistake; but we're thinking that *consecutive* duplicate properties are very, very rarely a mistake. We've worked on large teams, too, and have not seen *consecutive* duplicate property mistakes.

Besides, this is a move towards *more* leniency, which is probably the preferred move for our standard config when we have competing opinions.

**Comment by ArmorDarks** [comment]
I understand that decision is already been made, and there is no point in arguing with it.

Though, I'd really want maintainers of this config to realize, that "that error is easy to spot" is poor guidance for writing rules.

**Comment by davidtheclark** [comment]
> "that error is easy to spot" is poor guidance for writing rules.

Agreed — to be clear, that's not the justification. "Consecutive duplicate properties are very, very rarely a mistake": that's the justification. And: more leniency is preferable when we have competing opinions.

**Comment by ArmorDarks** [comment]
I'd aim for worst scenario, that's the point of linters, to catch errors, even if they are rare.

And I'm afraid it's impossible to talk about leniency here. It catches all errors, or misses some of them. Until we'll get AI for linting our files, there is no "middle" option here.

From my perspective, it's worse to allow linter to miss part of errors based just on assumption, and even worse to enforce that assumption on community.

But you're the boss, so, let it be :-)

**Comment by mrhyde** [comment]
> Consecutive duplicate properties are very, very rarely a mistake

Even by a beginner developer? Because, correct me if I'm wrong, I was always thinking that linters are handy tools created to help not only professional and experienced developers, but to those that are on their path to becoming one.

**Comment by davidtheclark** [comment]
> Even by a beginner developer? 

That's what we're thinking, yes.

If others, like @ArmorDarks, disagree with this choice, please voice your opinion. We'll certainly take what you say into consideration.

Again, though, I need to reaffirm the principles behind the change, because I think some misconceptions are being repeated above. 

- Nothing is being "enforced" on anybody. The goal of this config is to provide some sane defaults, and thereby minimize the amount of configuration that users will need to write. It's absolutely, 100% expected that users will extend this config and then customize according to their preferences.
- stylelint cannot know whether consecutive duplicate properties with different values is a mistake or *an intentional and standard usage of CSS's features*. We added this option because we think that the pattern is much more likely to be intentional than mistaken. And its intentional usage is totally standard. That's not to say that nobody ever makes this mistake. Most importantly, if they do *make* this mistake stylelint can't really know that it *is* a mistake. Whether it is a mistake or not depends on your context (what tools you're using, what browsers you're targeting, etc.). In ambiguous situations like these, we lean on the side of leniency for this config. Users that want to be more strict can, as mentioned above, extend and add to the config.

What would get us to switch? If we came under the impression that this pattern is *more often a mistake than an intentional usage of CSS's features*, so that having this option turned on means *more* users need to extend & modify this config than otherwise.
