### ISSUE TITLE
at-rule-empty-line-before should ignore else

### ISSUE THREAD

**Issue by merlinpatt** [stylelint/stylelint-config-standard#70]
at-rule-empty-line-before currently only ignores after-comment. It should also ignore else blocks.

The below is considered an error, and it shouldn't be. I have never seen if / else blocks separated by newlines.

```
@if (...) {
  ...
}
@else (...) {

}
```

**Comment by hudochenkov** [comment]
Reconfigure `at-rule-empty-line-before` using [`ignoreAtRules: ["else"]`](https://stylelint.io/user-guide/rules/at-rule-empty-line-before/#ignoreatrules-array-of-at-rules), and use [`scss/at-else-empty-line-before`](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-else-empty-line-before/README.md).

**Comment by jeddy3** [comment]
@merlinpatt The `stylelint-scss` team also provide [two example configurations](https://github.com/kristerkari/stylelint-scss/blob/master/docs/examples/if-else.md). 

There's also [an issue over there](https://github.com/kristerkari/stylelint-scss/issues/91) to create a standard config for SCSS. Please consider helping out with that project if you'd like to see something come if it. 

This config, like the stylelint core itself, is aimed at the standard CSS language.  However, stylelint also provides means of extensibility (plugins, extendable configs etc) for non-standard language extensions. That's why there's a team over at `stylelint-scss` who are building on top of stylelint to tailor it for all the non-standard language extensions introduced in SCSS.
